services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inkmatch
    ports:
      - 5432:5432

  adonis:
    container_name: adonis
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: production
    ports:
      - ${PORT-3333}:${PORT-3333}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/build

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/staging-inkmatch.devamarion.fr/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/staging-inkmatch.devamarion.fr/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - adonis

volumes:
  postgres_volume:
