services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inkmatch
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  adonis:
    container_name: adonis
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT-3333}:${PORT-3333}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: dumb-init node --inspect=0.0.0.0 ace serve --watch

volumes:
  postgres_volume:
