---
- name: Deploy API
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}"
    ansistrano_deploy_to: "/root/app"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/after-symlink.yml"
    ansistrano_git_repo: "git@github.com:Les-Capybaras/inkmatch-back-end.git"
    ansistrano_git_branch: "staging"
    ansistrano_git_identity_key_path: "/root/.ssh/id_ed25519"
  roles:
    - { role: ansistrano.deploy }