---
- name: Deploy API
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../"
    ansistrano_deploy_to: "/app"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/after-symlink.yml"
    ansistrano_version_dir: "releases"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_deploy_via: "git"
    ansistrano_git_branch: "{{ branch }}"
    ansistrano_git_repo: "git@github.com:Les-Capybaras/inkmatch-back-end.git"
    ansistrano_keep_releases: 3
    ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_ed25519"
    ansistrano_git_ssh_opts: "-o StrictHostKeyChecking=no"
    ansistrano_allow_anonymous_stats: no

  roles:
    - { role: ansistrano.deploy }