---
- name: Deploy API
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../"
    ansistrano_deploy_to: "/app"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/after-symlink.yml"
  roles:
    - { role: ansistrano.deploy }