---
- name: Update code and run Docker container
  hosts: all
  become: true

  tasks:
    - name: Clone or pull code from Git repository
      git:
        repo: git@github.com:Les-Capybaras/inkmatch-back-end.git
        dest: /root/inkmatch-back-end
        version: staging
        update: yes

    - name: Copy .env file
      copy:
        src: /root/inkmatch-back-end/.env.staging
        dest: /root/inkmatch-back-end/.env

    - name: Build and run Docker container
      command: docker compose -f docker-compose.prod.yml up -d --build
      args:
        chdir: /root/inkmatch-back-end

    - name: Remove old Docker images
      command: docker image prune -f

    - name: Remove old Docker containers
      command: docker container prune -f