name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run with Docker Compose
        uses: docker/compose@v1
        with:
          up: true
          build: true
          env_file: /api/env.dist

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - name: Run tests
        working-directory: ./api
        run: npm test

      - name: Build
        working-directory: ./api
        run: npm run build
