name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d --build

  QA:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - name: Run audit
        working-directory: ./api
        run: npm audit

      - name: Run lint
        working-directory: ./api
        run: npm run lint:ci

  Tests:
    runs-on: ubuntu-latest
    needs: Build

    services:
      database:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: ChangeMe!
          MYSQL_DATABASE: changeme
          MYSQL_USER: changeme
          MYSQL_PASSWORD: ChangeMe!
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Build and start services
        working-directory: ./api
        run: npm install

      - name: Run tests
        working-directory: ./api
        run: npm run test:ci

      - name: Run functional tests
        working-directory: ./api
        run: npm run functional:test:ci

      - name: Run code coverage
        working-directory: ./api
        run: npm run test:coverage:ci

  Deploy:
    runs-on: ubuntu-latest
    needs: Tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy App
        uses: appleboy@ssh-action@v0.4.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /inkmatch-back-end
            git pull
            docker compose up -d --build
