name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and start services
        run: docker compose up -d --build

      - name: Audit Packages
        run: docker exec inkmatch-back-end-api-1 npm audit

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run tests
        working-directory: ./api
        run: |
          npm install
          npm run test
