name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and start services
        run: docker compose -f docker-compose.ci.yml up -d --build

      - name: Wait for database
        run: |
          until docker compose -f docker-compose.ci.yml exec -T database mysqladmin ping --silent; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Audit Packages
        run: docker compose -f docker-compose.ci.yml exec -T api npm audit

      - name: Run tests
        run: docker compose -f docker-compose.ci.yml exec -T api npm test
